name : Navaneeth
on : push
jobs :
    greet:
        runs-on : ubuntu-latest
        steps :
            - name : Greet the user
              run : echo "Hello, Navaneeth! Welcome to the GitHub Actions workflow."
            - name: Setup Node.js
              run : node -v